#!/usr/bin/env python3
"""Regenerate the vendored windows-bindgen output for the Store's InstallControl API.

`crates/fsw-cli/src/update/install_control.rs` is `windows-bindgen` output for
`Windows.ApplicationModel.Store.Preview.InstallControl` -- the `AppInstallManager`
surface winget drives, which the published `windows` crate 0.62.2 does not
contain at all (the entire `Windows.ApplicationModel.Store` tree is absent). The
types come from the Windows SDK's own `Windows.winmd`, so the file is generated
once and committed, exactly as `docs/dependencies.md` prescribes for option 3
("windows-bindgen output, committed to the repo, regenerated in CI with
`git diff --exit-code`").

Two things about the generator are worth knowing before running this:

  * **`windows-bindgen` is a library, not a binary.** `cargo install
    windows-bindgen` fails with "can't be used with libraries". This script
    therefore writes a five-line driver crate into a temporary directory, pins
    it at `=0.62.1`, and runs `windows_bindgen::bindgen(args)` from there.
  * **The generator shells out to `rustfmt`** for the final formatting, so its
    output is only reproducible under a fixed rustfmt. The driver is run with
    `RUSTUP_TOOLCHAIN` forced to the channel in `rust-toolchain.toml`, and the
    script refuses to run when that rustfmt is missing rather than silently
    emitting the unformatted fallback.

Usage:
    python3 tools/regen_install_control.py           # rewrite the vendored file
    python3 tools/regen_install_control.py --check   # CI: is the file current?
    python3 tools/regen_install_control.py --print-winmd-version

`--check` is what `.github/workflows/build.yml` runs on the Windows job, and only
when the runner carries the exact SDK version recorded below: a different
`Windows.winmd` legitimately produces different bindings, and a diff against it
would be noise rather than a stale-file signal.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "crates" / "fsw-cli" / "src" / "update" / "install_control.rs"

# ---------------------------------------------------------------------------
# The recipe. Every value here is also recorded in the generated file's header,
# so a reader never has to come back to this script to know what produced it.
# ---------------------------------------------------------------------------

NAMESPACE = "Windows.ApplicationModel.Store.Preview.InstallControl"
BINDGEN_VERSION = "0.62.1"
# The `windows` crate the generated code is compiled against, and the one whose
# missing namespace is the reason this file exists.
WINDOWS_CRATE_VERSION = "0.62.2"
WINMD_VERSION = "10.0.26100.0"
WINMD_WINDOWS_PATH = (
    r"C:\Program Files (x86)\Windows Kits\10\UnionMetadata"
    rf"\{WINMD_VERSION}\Windows.winmd"
)
WINMD_WSL_PATH = (
    "/mnt/c/Program Files (x86)/Windows Kits/10/UnionMetadata"
    f"/{WINMD_VERSION}/Windows.winmd"
)

# `--flat` drops the five-deep `Windows::ApplicationModel::Store::Preview::
# InstallControl` module nest: the file *is* the namespace, so the nest would
# only lengthen every use site.
#
# `--reference windows,skip-root,Windows.Foundation` points the four
# `TypedEventHandler` parameters at the `windows` crate the CLI already depends
# on instead of regenerating them. `Windows.Foundation` is the *only* reference:
# `IAsyncOperation` and `IVectorView` are special-cased by the generator onto
# `windows-future` / `windows-collections`, and deliberately leaving
# `Windows.System` and `Windows.Management.Deployment` unreferenced makes the
# generator skip the 15 `*ForUserAsync` / `PackageVolume` methods (their vtable
# slots survive as `usize` placeholders, so layout is unaffected) rather than
# forcing two more `windows` features into the binary for methods this product
# never calls.
FLAGS = ["--flat"]
REFERENCE = "windows,skip-root,Windows.Foundation"

# Methods the generator drops, listed here so the count is a checked fact
# rather than a memory: adding a reference above would change it.
SKIPPED_METHOD_COUNT = 15

HEADER_TEMPLATE = '''\
//! Vendored `windows-bindgen` output for the Microsoft Store's install-control
//! API -- **generated, do not edit**.
//!
//! Regenerate with `python3 tools/regen_install_control.py`; `--check` fails
//! when this file has drifted, and the Windows CI job runs it whenever the
//! runner carries the recorded SDK.
//!
//! | | |
//! |---|---|
//! | Namespace | `{namespace}` |
//! | Metadata | `{winmd}` (Windows SDK {winmd_version}) |
//! | Generator | `windows-bindgen` {bindgen_version} |
//!
//! Generated by `windows_bindgen::bindgen` with exactly these arguments:
//!
//! ```text
{command_block}
//! ```
//!
//! `windows-bindgen` is a library rather than an installable binary, so the
//! regeneration script drives it from a throwaway crate pinned at
//! `windows-bindgen = "={bindgen_version}"`, under the `rust-toolchain.toml`
//! channel (the generator shells out to `rustfmt`, so the formatting is only
//! reproducible under a fixed one).
//!
//! Why this is vendored at all: the published `windows` crate {windows_version}
//! carries no `Windows.ApplicationModel.Store` tree whatsoever, and this
//! namespace is where `AppInstallManager` lives -- the Store install path winget
//! itself uses. See `docs/dependencies.md`.
//!
//! {skipped} methods are absent by design: every `*ForUserAsync` overload and
//! everything typed on `Windows.Management.Deployment.PackageVolume`. They are
//! the only members that would drag `Windows.System` /
//! `Windows.Management.Deployment` in as extra `windows` features, this product
//! calls none of them, and the generator keeps their vtable slots as `usize`
//! placeholders so interface layout is untouched.
//!
//! The lint allowances here are the generator's own plus one this workspace
//! needs, and both are scoped to this file. No hand-written code in this crate
//! carries any.

// The generated block below allows `clippy::all`; this workspace additionally
// turns on `clippy::pedantic`, which no generated binding satisfies (81
// warnings from this file without it).
#![allow(clippy::pedantic)]

'''

DRIVER_CARGO_TOML = f'''\
[package]
name = "fsw-install-control-bindgen"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
windows-bindgen = "={BINDGEN_VERSION}"

[workspace]
'''

DRIVER_MAIN_RS = '''\
fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    // `bindgen` is #[must_use]: it returns the "skipping ..." warnings.
    let warnings = windows_bindgen::bindgen(&args);
    eprint!("{warnings}");
}
'''


def pinned_toolchain() -> str:
    """The channel from `rust-toolchain.toml`.

    The driver crate lives outside the repository, so the toolchain file does
    not apply to it automatically; forcing `RUSTUP_TOOLCHAIN` is what keeps the
    `rustfmt` the generator invokes -- and therefore the output bytes -- the
    same here and in CI.
    """
    text = (REPO_ROOT / "rust-toolchain.toml").read_text(encoding="utf-8")
    match = re.search(r'^\s*channel\s*=\s*"([^"]+)"', text, re.MULTILINE)
    if not match:
        raise SystemExit("rust-toolchain.toml has no [toolchain] channel")
    return match.group(1)


def locate_winmd() -> Path:
    """The SDK metadata file, overridable with `FSW_WINMD`."""
    override = os.environ.get("FSW_WINMD")
    candidates = [Path(override)] if override else [
        Path(WINMD_WINDOWS_PATH) if os.name == "nt" else Path(WINMD_WSL_PATH)
    ]
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    raise SystemExit(
        f"Windows SDK metadata not found: {candidates[0]}\n"
        f"Install the {WINMD_VERSION} SDK, or point FSW_WINMD at a Windows.winmd."
    )


def bindgen_args(winmd: str, out: str) -> list[str]:
    return [
        "--in", winmd,
        "--out", out,
        *FLAGS,
        "--reference", REFERENCE,
        "--filter", NAMESPACE,
    ]


def command_block() -> str:
    """The recipe as it goes into the generated file's header."""
    lines = ["//! windows_bindgen::bindgen(["]
    # Forward slashes and a literal string, never a `Path`: this text is
    # committed, and a `Path` would render with backslashes on Windows and make
    # `--check` fail there for no reason.
    for argument in bindgen_args(
        WINMD_WINDOWS_PATH, "crates/fsw-cli/src/update/install_control.rs"
    ):
        lines.append(f'//!     "{argument}",')
    lines.append("//! ])")
    return "\n".join(lines)


def header() -> str:
    return HEADER_TEMPLATE.format(
        namespace=NAMESPACE,
        winmd=WINMD_WINDOWS_PATH,
        winmd_version=WINMD_VERSION,
        bindgen_version=BINDGEN_VERSION,
        windows_version=WINDOWS_CRATE_VERSION,
        command_block=command_block(),
        skipped=SKIPPED_METHOD_COUNT,
    )


def run(command: list[str], *, cwd: Path, env: dict[str, str]) -> None:
    result = subprocess.run(command, cwd=cwd, env=env)
    if result.returncode != 0:
        raise SystemExit(f"`{' '.join(command)}` failed with {result.returncode}")


def generate(verbose: bool) -> str:
    winmd = locate_winmd()
    toolchain = pinned_toolchain()
    env = dict(os.environ)
    env["RUSTUP_TOOLCHAIN"] = toolchain

    # The generator's rustfmt fallback is silent -- it emits unformatted tokens
    # and exits 0 -- so prove rustfmt is there before trusting the bytes.
    probe = subprocess.run(
        ["rustfmt", "--version"], capture_output=True, text=True, env=env
    )
    if probe.returncode != 0:
        raise SystemExit(
            f"rustfmt is not available for toolchain {toolchain}; "
            f"`rustup component add rustfmt --toolchain {toolchain}` first."
        )
    if verbose:
        print(f"toolchain {toolchain}: {probe.stdout.strip()}")
        print(f"metadata:  {winmd}")

    with tempfile.TemporaryDirectory(prefix="fsw-install-control-") as scratch:
        crate = Path(scratch)
        (crate / "src").mkdir()
        (crate / "Cargo.toml").write_text(DRIVER_CARGO_TOML, encoding="utf-8")
        (crate / "src" / "main.rs").write_text(DRIVER_MAIN_RS, encoding="utf-8")
        generated = crate / "install_control.rs"
        run(["cargo", "build", "--quiet"], cwd=crate, env=env)
        run(
            ["cargo", "run", "--quiet", "--"]
            + bindgen_args(str(winmd), str(generated)),
            cwd=crate,
            env=env,
        )
        body = generated.read_text(encoding="utf-8")

    return header() + body


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate crates/fsw-cli/src/update/install_control.rs.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed file differs from a fresh generation",
    )
    parser.add_argument(
        "--print-winmd-version",
        action="store_true",
        help="print the SDK version this file was generated from, and exit",
    )
    args = parser.parse_args(argv)

    if args.print_winmd_version:
        print(WINMD_VERSION)
        return 0

    fresh = generate(verbose=not args.check)

    if args.check:
        current = (
            OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.is_file() else ""
        )
        if current != fresh:
            print(
                f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is out of date: regenerate it "
                "with `python3 tools/regen_install_control.py`.",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is current.")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_PATH.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(fresh)
    print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} ({len(fresh)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
